
FROM golang:alpine AS builder

WORKDIR /app

RUN apk add --no-cache build-base

COPY go.* ./
RUN go mod download

COPY . .

RUN go build -o service-podof ./cmd/service-podof/grpc-server/main.go


FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/service-podof .


COPY .env /app/.env

EXPOSE 3000

CMD ["./service-podof"]