/*
backend service

Сервис для управления ПВЗ и приемкой товаров

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PvzGet200ResponseInnerReceptionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PvzGet200ResponseInnerReceptionsInner{}

// PvzGet200ResponseInnerReceptionsInner struct for PvzGet200ResponseInnerReceptionsInner
type PvzGet200ResponseInnerReceptionsInner struct {
	Reception *Reception `json:"reception,omitempty"`
	Products []Product `json:"products,omitempty"`
}

// NewPvzGet200ResponseInnerReceptionsInner instantiates a new PvzGet200ResponseInnerReceptionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPvzGet200ResponseInnerReceptionsInner() *PvzGet200ResponseInnerReceptionsInner {
	this := PvzGet200ResponseInnerReceptionsInner{}
	return &this
}

// NewPvzGet200ResponseInnerReceptionsInnerWithDefaults instantiates a new PvzGet200ResponseInnerReceptionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPvzGet200ResponseInnerReceptionsInnerWithDefaults() *PvzGet200ResponseInnerReceptionsInner {
	this := PvzGet200ResponseInnerReceptionsInner{}
	return &this
}

// GetReception returns the Reception field value if set, zero value otherwise.
func (o *PvzGet200ResponseInnerReceptionsInner) GetReception() Reception {
	if o == nil || IsNil(o.Reception) {
		var ret Reception
		return ret
	}
	return *o.Reception
}

// GetReceptionOk returns a tuple with the Reception field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PvzGet200ResponseInnerReceptionsInner) GetReceptionOk() (*Reception, bool) {
	if o == nil || IsNil(o.Reception) {
		return nil, false
	}
	return o.Reception, true
}

// HasReception returns a boolean if a field has been set.
func (o *PvzGet200ResponseInnerReceptionsInner) HasReception() bool {
	if o != nil && !IsNil(o.Reception) {
		return true
	}

	return false
}

// SetReception gets a reference to the given Reception and assigns it to the Reception field.
func (o *PvzGet200ResponseInnerReceptionsInner) SetReception(v Reception) {
	o.Reception = &v
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *PvzGet200ResponseInnerReceptionsInner) GetProducts() []Product {
	if o == nil || IsNil(o.Products) {
		var ret []Product
		return ret
	}
	return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PvzGet200ResponseInnerReceptionsInner) GetProductsOk() ([]Product, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *PvzGet200ResponseInnerReceptionsInner) HasProducts() bool {
	if o != nil && !IsNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []Product and assigns it to the Products field.
func (o *PvzGet200ResponseInnerReceptionsInner) SetProducts(v []Product) {
	o.Products = v
}

func (o PvzGet200ResponseInnerReceptionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PvzGet200ResponseInnerReceptionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reception) {
		toSerialize["reception"] = o.Reception
	}
	if !IsNil(o.Products) {
		toSerialize["products"] = o.Products
	}
	return toSerialize, nil
}

type NullablePvzGet200ResponseInnerReceptionsInner struct {
	value *PvzGet200ResponseInnerReceptionsInner
	isSet bool
}

func (v NullablePvzGet200ResponseInnerReceptionsInner) Get() *PvzGet200ResponseInnerReceptionsInner {
	return v.value
}

func (v *NullablePvzGet200ResponseInnerReceptionsInner) Set(val *PvzGet200ResponseInnerReceptionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePvzGet200ResponseInnerReceptionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePvzGet200ResponseInnerReceptionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePvzGet200ResponseInnerReceptionsInner(val *PvzGet200ResponseInnerReceptionsInner) *NullablePvzGet200ResponseInnerReceptionsInner {
	return &NullablePvzGet200ResponseInnerReceptionsInner{value: val, isSet: true}
}

func (v NullablePvzGet200ResponseInnerReceptionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePvzGet200ResponseInnerReceptionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


