/*
backend service

Сервис для управления ПВЗ и приемкой товаров

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DummyLoginPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DummyLoginPostRequest{}

// DummyLoginPostRequest struct for DummyLoginPostRequest
type DummyLoginPostRequest struct {
	Role string `json:"role"`
}

type _DummyLoginPostRequest DummyLoginPostRequest

// NewDummyLoginPostRequest instantiates a new DummyLoginPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDummyLoginPostRequest(role string) *DummyLoginPostRequest {
	this := DummyLoginPostRequest{}
	this.Role = role
	return &this
}

// NewDummyLoginPostRequestWithDefaults instantiates a new DummyLoginPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDummyLoginPostRequestWithDefaults() *DummyLoginPostRequest {
	this := DummyLoginPostRequest{}
	return &this
}

// GetRole returns the Role field value
func (o *DummyLoginPostRequest) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *DummyLoginPostRequest) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *DummyLoginPostRequest) SetRole(v string) {
	o.Role = v
}

func (o DummyLoginPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DummyLoginPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *DummyLoginPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDummyLoginPostRequest := _DummyLoginPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDummyLoginPostRequest)

	if err != nil {
		return err
	}

	*o = DummyLoginPostRequest(varDummyLoginPostRequest)

	return err
}

type NullableDummyLoginPostRequest struct {
	value *DummyLoginPostRequest
	isSet bool
}

func (v NullableDummyLoginPostRequest) Get() *DummyLoginPostRequest {
	return v.value
}

func (v *NullableDummyLoginPostRequest) Set(val *DummyLoginPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDummyLoginPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDummyLoginPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDummyLoginPostRequest(val *DummyLoginPostRequest) *NullableDummyLoginPostRequest {
	return &NullableDummyLoginPostRequest{value: val, isSet: true}
}

func (v NullableDummyLoginPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDummyLoginPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


