/*
backend service

Сервис для управления ПВЗ и приемкой товаров

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductsPostRequest{}

// ProductsPostRequest struct for ProductsPostRequest
type ProductsPostRequest struct {
	Type string `json:"type"`
	PvzId string `json:"pvzId"`
}

type _ProductsPostRequest ProductsPostRequest

// NewProductsPostRequest instantiates a new ProductsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductsPostRequest(type_ string, pvzId string) *ProductsPostRequest {
	this := ProductsPostRequest{}
	this.Type = type_
	this.PvzId = pvzId
	return &this
}

// NewProductsPostRequestWithDefaults instantiates a new ProductsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductsPostRequestWithDefaults() *ProductsPostRequest {
	this := ProductsPostRequest{}
	return &this
}

// GetType returns the Type field value
func (o *ProductsPostRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProductsPostRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProductsPostRequest) SetType(v string) {
	o.Type = v
}

// GetPvzId returns the PvzId field value
func (o *ProductsPostRequest) GetPvzId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PvzId
}

// GetPvzIdOk returns a tuple with the PvzId field value
// and a boolean to check if the value has been set.
func (o *ProductsPostRequest) GetPvzIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PvzId, true
}

// SetPvzId sets field value
func (o *ProductsPostRequest) SetPvzId(v string) {
	o.PvzId = v
}

func (o ProductsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["pvzId"] = o.PvzId
	return toSerialize, nil
}

func (o *ProductsPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"pvzId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductsPostRequest := _ProductsPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductsPostRequest)

	if err != nil {
		return err
	}

	*o = ProductsPostRequest(varProductsPostRequest)

	return err
}

type NullableProductsPostRequest struct {
	value *ProductsPostRequest
	isSet bool
}

func (v NullableProductsPostRequest) Get() *ProductsPostRequest {
	return v.value
}

func (v *NullableProductsPostRequest) Set(val *ProductsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductsPostRequest(val *ProductsPostRequest) *NullableProductsPostRequest {
	return &NullableProductsPostRequest{value: val, isSet: true}
}

func (v NullableProductsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


