/*
backend service

Сервис для управления ПВЗ и приемкой товаров

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReceptionsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReceptionsPostRequest{}

// ReceptionsPostRequest struct for ReceptionsPostRequest
type ReceptionsPostRequest struct {
	PvzId string `json:"pvzId"`
}

type _ReceptionsPostRequest ReceptionsPostRequest

// NewReceptionsPostRequest instantiates a new ReceptionsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceptionsPostRequest(pvzId string) *ReceptionsPostRequest {
	this := ReceptionsPostRequest{}
	this.PvzId = pvzId
	return &this
}

// NewReceptionsPostRequestWithDefaults instantiates a new ReceptionsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceptionsPostRequestWithDefaults() *ReceptionsPostRequest {
	this := ReceptionsPostRequest{}
	return &this
}

// GetPvzId returns the PvzId field value
func (o *ReceptionsPostRequest) GetPvzId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PvzId
}

// GetPvzIdOk returns a tuple with the PvzId field value
// and a boolean to check if the value has been set.
func (o *ReceptionsPostRequest) GetPvzIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PvzId, true
}

// SetPvzId sets field value
func (o *ReceptionsPostRequest) SetPvzId(v string) {
	o.PvzId = v
}

func (o ReceptionsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReceptionsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pvzId"] = o.PvzId
	return toSerialize, nil
}

func (o *ReceptionsPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pvzId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceptionsPostRequest := _ReceptionsPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReceptionsPostRequest)

	if err != nil {
		return err
	}

	*o = ReceptionsPostRequest(varReceptionsPostRequest)

	return err
}

type NullableReceptionsPostRequest struct {
	value *ReceptionsPostRequest
	isSet bool
}

func (v NullableReceptionsPostRequest) Get() *ReceptionsPostRequest {
	return v.value
}

func (v *NullableReceptionsPostRequest) Set(val *ReceptionsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReceptionsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReceptionsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceptionsPostRequest(val *ReceptionsPostRequest) *NullableReceptionsPostRequest {
	return &NullableReceptionsPostRequest{value: val, isSet: true}
}

func (v NullableReceptionsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceptionsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


