/*
backend service

Сервис для управления ПВЗ и приемкой товаров

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterPostRequest{}

// RegisterPostRequest struct for RegisterPostRequest
type RegisterPostRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
	Role string `json:"role"`
}

type _RegisterPostRequest RegisterPostRequest

// NewRegisterPostRequest instantiates a new RegisterPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterPostRequest(email string, password string, role string) *RegisterPostRequest {
	this := RegisterPostRequest{}
	this.Email = email
	this.Password = password
	this.Role = role
	return &this
}

// NewRegisterPostRequestWithDefaults instantiates a new RegisterPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterPostRequestWithDefaults() *RegisterPostRequest {
	this := RegisterPostRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *RegisterPostRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RegisterPostRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RegisterPostRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *RegisterPostRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RegisterPostRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RegisterPostRequest) SetPassword(v string) {
	o.Password = v
}

// GetRole returns the Role field value
func (o *RegisterPostRequest) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *RegisterPostRequest) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *RegisterPostRequest) SetRole(v string) {
	o.Role = v
}

func (o RegisterPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *RegisterPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterPostRequest := _RegisterPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterPostRequest)

	if err != nil {
		return err
	}

	*o = RegisterPostRequest(varRegisterPostRequest)

	return err
}

type NullableRegisterPostRequest struct {
	value *RegisterPostRequest
	isSet bool
}

func (v NullableRegisterPostRequest) Get() *RegisterPostRequest {
	return v.value
}

func (v *NullableRegisterPostRequest) Set(val *RegisterPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterPostRequest(val *RegisterPostRequest) *NullableRegisterPostRequest {
	return &NullableRegisterPostRequest{value: val, isSet: true}
}

func (v NullableRegisterPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


